#!/bin/bash

sudo apt-get install \
    ninja-build \
    cmake \
    make \
    speex \
    pkg-config \
    python3-pip \
    libidn2-dev \
    libdrm-dev \
    libspeex-dev \
    libudev-dev \
    libbz2-dev \
    git \
    p7zip-full \
    binutils \
    bzip2 \
    libaio-dev \
    libxml2-dev \
    lzop \
    ncurses-term \
    openssl \
    libpam0g-dev \
    libtool \
    libltdl-dev \
    libao-dev \
    libavahi-compat-libdnssd-dev \
    pcre2-utils \
    libass-dev \
    fontconfig \
    libfribidi-dev \
    libtinyxml-dev \
    libjpeg-turbo8-dev \
    zlib1g \
    libbluray-dev \
    libcec-dev \
    libdvdnav-dev \
    libdvdread-dev \
    libusb-1.0-0-dev \
    libxslt1-dev \
    xsltproc \
    libiso9660-dev \
    libcap-dev \
    libnfs-dev \
    libplist-dev \
    libsmbclient-dev \
    libcrossguid-dev \
    libcurl4-openssl-dev \
    libflatbuffers-dev \
    libfmt-dev \
    libfstrcmp-dev \
    rapidjson-dev \
    libspdlog-dev \
    libsqlite3-dev \
    libgbm-dev \
    libinput-dev \
    libxkbcommon-dev \
    libgif-dev \
    openjdk-11-jre-headless \
    swig \
    libbluetooth-dev \
    libegl1-mesa-dev
sudo -H pip3 install meson
sudo ldconfig